import { writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import type { ProjectConfig } from "./types.js";

export function writeEnvFile(config: ProjectConfig): void {
  const targetDir = resolve(config.targetDir);
  const lines = [
    "# Generated by create-shuriken",
    "",
    'NODE_ENV="development"',
    "",
    `DATABASE_URL=postgresql://postgres:postgres@localhost:5432/${config.dbName}`,
    "",
    "# REDIS_URL=redis://localhost:6379",
    "",
    `NEXT_PUBLIC_MAIN_APP_URL="${config.mainAppUrl}"`,
    `NEXT_PUBLIC_LANDING_URL="${config.landingUrl}"`,
    "",
    `NEXT_PUBLIC_APP_NAME="${config.appName}"`,
    "",
    'LOG_LEVEL="debug"',
    "",
    "# RESEND_API_KEY=",
    "# RESEND_FROM_EMAIL=",
    "",
  ];

  if (config.seedAdmin) {
    lines.push(
      `ADMIN_EMAIL="${config.adminEmail}"`,
      `ADMIN_PASSWORD="${config.adminPassword}"`,
      `ADMIN_NAME="${config.adminName}"`,
      "",
    );
  } else {
    lines.push(
      "# ADMIN_EMAIL=admin@example.com",
      "# ADMIN_PASSWORD=Admin@123",
      "# ADMIN_NAME=System Administrator",
      "",
    );
  }

  writeFileSync(join(targetDir, ".env"), lines.join("\n"), "utf8");
}
